### ISSUE TITLE
Secure API links return error

### ISSUE THREAD

**Issue by PNMIC** [VinceG/USPS-php-api#10]
I had the old USBase.php from 1-2 years ago and just updated to the latest one that says fixes ssl issue. With both TEST and Production modes, I get this error:

"80040B1AAPI Authorization failure. CityStateLookup is not a valid API name for this protocol.USPSCOM::DoAuth"

So I used the unsecure api links from the old USBase.php and it works fine, both test and production mode. These links are as follows:

const LIVE_API_URL = 'http://production.shippingapis.com/ShippingAPI.dll';
const TEST_API_URL = 'http://testing.shippingapis.com/ShippingAPITest.dll';

So unless there is something else wrong on my side, I don't think the SSL issue has been resolved. Unless USPS changed something...

**Comment by narendratops** [comment]
using your library i get the class not found error.can u help me to integrate.i use directly  demo.

**Comment by greggles** [comment]
I've asked them which APIs require HTTP vs. HTTPS. They got back saying that most are supported over HTTPS and only a few informational listings are not supported on HTTPS. I asked about this list specifically and hope to get an answer in a day or so, then we can move forward:

* RateV2
* RateV4
* IntlRateV2
* Verify
* ZipCodeLookup
* CityStateLookup
* TrackV2
* FirstClassMail
* SDCGetLocations

**Comment by greggles** [comment]
Here's their response:

RateV2 - Not actively supported
RateV4 - HTTPS, HTTP
IntlRateV2 - HTTPS, HTTP
Verify - HTTPS, HTTP
ZipCodeLookup - HTTPS, HTTP
CityStateLookup - HTTPS, HTTP
TrackV2 - HTTPS, HTTP
FirstClassMail - HTTP
SDCGetLocations - HTTP

So, I guess it's going to be necessary to have a per-method API endpoint.
