### ISSUE TITLE
2015 - isn't it time yet to use autoloaders?

### ISSUE THREAD

**Issue by jamm** [VinceG/USPS-php-api#17]
Really hard to add this library to code, built with using autoloading. All those 'require' looks archaic and calling code doesn't know and shouldn't know folders structure of this library.

**Comment by VinceG** [comment]
@jamm maybe you can help by submitting a pull request to use composer and autoloading the classes?

**Comment by wjgilmore** [comment]
Just an FYI this has since been forked and turned into a package: https://packagist.org/packages/alexanderreiff/usps-php-api

**Comment by VinceG** [comment]
@jamm @wjgilmore  perfect thanks.
