### ISSUE TITLE
delivery calculator error

### ISSUE THREAD

**Issue by josephmario** [VinceG/USPS-php-api#28]
We got problem in servicedeliverycalculator.php,

string(223) " 80040B1AAPI Authorization failure. SDCGetLocations is not a valid API name for this protocol.USPSCOM::DoAuth" array(1) { ["Error"]=> array(3) { ["Number"]=> string(8) "80040B1A" ["Description"]=> string(85) "API Authorization failure. SDCGetLocations is not a valid API name for this protocol." ["Source"]=> string(15) "USPSCOM::DoAuth" } } Error: API Authorization failure. SDCGetLocations is not a valid API name for this protocol.

and our code 

<?php
// Load the class
require_once('../USPSServiceDeliveryCalculator.php');

// Initiate and set the username provided from usps
$delivery = new USPSServiceDeliveryCalculator('939RESOU3678');

// During test mode this seems not to always work as expected
$delivery->setTestMode(true);

// Add the zip code we want to lookup the city and state
$delivery->addRoute(3, '16866', '19141');

// Perform the call and print out the results
var_dump($delivery->getServiceDeliveryCalculation());
var_dump($delivery->getArrayResponse());

// Check if it was completed
if($delivery->isSuccess()) {
  echo 'Done';
} else {
  echo 'Error: ' . $delivery->getErrorMessage();
}
?>

We follow the rules and we just go error please reply to us thank you

**Comment by R-K-H** [comment]
Just ask USPS to move you to production. Let me know if that fixes it.
