### ISSUE TITLE
PHP 7 Compatability

### ISSUE THREAD

**Issue by greggles** [VinceG/USPS-php-api#35]
Has anyone tested this with php 7?

**Comment by VinceG** [comment]
We've been using this with php7 on production ... no issues 

Please excuse my brevity, sent from my iPhone

**Comment by VinceG** [comment]
@greggles

**Comment by greggles** [comment]
Great news. Thanks for responding so quickly, @VinceG 

It seems good to list some compatability in the README - if you agree I'm happy to open a PR to add that.

**Comment by VinceG** [comment]
@greggles Please. Thank You.

**Comment by greggles** [comment]
This issue can be closed :)

**Comment by greggles** [comment]
Oh, and I can do that! :)
