### ISSUE TITLE
Authorization failure. Perhaps username and/or password is incorrect.

### ISSUE THREAD

**Issue by nikunjsilvercayde** [VinceG/USPS-php-api#51]
Hello 

In your api we just need to pass username only?

$verify = new \USPS\AddressVerify('XXX');

Where we can set password?

Because It's giving me below error.

80040B1AAuthorization failure. Perhaps username and/or password is incorrect.USPSCOM::DoAuthArray ( [Error] => Array ( [Number] => 80040B1A [Description] => Authorization failure. Perhaps username and/or password is incorrect. [Source] => USPSCOM::DoAuth ) ) bool(true) Error: Authorization failure. Perhaps username and/or password is incorrect.

**Comment by VinceG** [comment]
@nikunjsilvercayde This is for an older version of the API where password was not required. feel free to submit a PR to change this behavior to support passwords as well.
