### ISSUE TITLE
TrackConfirm Uses HTTP instead of HTTPS

### ISSUE THREAD

**Issue by tristanhall** [VinceG/USPS-php-api#59]
I've received a notice from USPS that they are discontinuing their unsecure HTTP endpoints stg-production.shippingapis.com and production.shippingapis.com.
The deadline for switching to HTTPS is 6/24/2021.

"Effective June 24th, 2021, Web Tools will remove support for all unsecure HTTP endpoints. After this change, all requests to an unsecure HTTP endpoint will fail when attempting to access the Web Tools APIs and integrators may see an error message"

One idea might be to add a class property that defines the protocol to use (defaulting to https), and introduce getter/setter methods (getProtocol/setProtocol?) to allow users to change the protocol as needed.

**Comment by VinceG** [comment]
Closed via #60
